- name: 'Creates /data/plan directory'
  file:
    path: /data/plan
    state: directory
    mode: 0775

- name: 'Creates /data/plan/logs directory'
  file:
    path: /data/plan/logs
    state: directory
    mode: 0775

- name: 'Creates /data/plan/rss directory'
  file:
    path: /data/plan/rss
    state: directory
    mode: 0775

- name: 'Copies /data/plan/plan-rss'
  copy:
    src: plan-rss
    dest: /data/plan/plan-rss
    mode: 0700

- name: 'Copies /data/plan/update-plan'
  copy:
    src: update-plan
    dest: /data/plan/update-plan
    mode: 0700

- name: 'Copies /data/plan/update-plan-rss'
  copy:
    src: update-plan-rss
    dest: /data/plan/update-plan-rss
    mode: 0700

- name: 'Installs cron job for daily refresh of plan file'
  cron:
    name: '.plan daily refresh'
    hour: '0'
    minute: '15'
    job: '/data/plan/update-plan'
# Execute this only if plan not present
- name: 'Executes update-plan'
  shell: /data/plan/update-plan

- name: 'Installs cron job for daily refresh of plan file'
  cron:
    name: '.plan daily refresh'
    hour: '0'
    minute: '16'
    job: '/data/plan/update-plan-rss'
# Execute this only if plan.xml not present
- name: 'Executes update-plan-rss'
  shell: /data/plan/update-plan-rss
