- name: 'Creates /data/plan directory'
  file:
    path: /data/plan
    state: directory
    mode: 0775

- name: 'Creates /data/plan/logs directory'
  file:
    path: /data/plan/logs
    state: directory
    mode: 0775

- name: 'Removes /data/plan/download-plan-rss'
  file:
    path: /data/plan/download-plan-rss
    state: absent

- name: 'Copies /data/plan/template-html.djhtml'
  copy:
    src: template-html.djhtml
    dest: /data/plan/template-html.djhtml
    mode: 0700

- name: 'Copies /data/plan/template-xml.djxml'
  copy:
    src: template-xml.djxml
    dest: /data/plan/template-xml.djxml
    mode: 0700

- name: 'Copies /data/plan/download-plan-convert'
  copy:
    src: download-plan-convert
    dest: /data/plan/download-plan-convert
    mode: 0700

- name: 'Copies /data/plan/update-dot-plan'
  copy:
    src: update-dot-plan
    dest: /data/plan/update-dot-plan
    mode: 0700

- name: 'Copies /data/plan/update-plan-xml'
  copy:
    src: update-plan-xml
    dest: /data/plan/update-plan-xml
    mode: 0700

- name: 'Copies /data/plan/update-plan-html'
  copy:
    src: update-plan-html
    dest: /data/plan/update-plan-html
    mode: 0700

- name: 'Uninstalls cron job for daily download of plan-rss'
  cron:
    name: 'plan-rss daily refresh'
    state: absent

- name: 'Installs cron job for daily download of plan-convert'
  cron:
    name: 'plan-convert daily refresh'
    hour: '3'
    minute: '0'
    job: '/data/plan/download-plan-convert'
- name: 'Executes download-plan-convert'
  shell: /data/plan/download-plan-convert
  args:
    creates: /data/plan/plan-convert

- name: 'Installs cron job for daily refresh of .plan file'
  cron:
    name: '.plan daily refresh'
    hour: '3'
    minute: '5'
    job: '/data/plan/update-dot-plan'
- name: 'Executes update-dot-plan'
  shell: /data/plan/update-dot-plan
  args:
    creates: /data/plan/.plan

- name: 'Installs cron job for daily refresh of plan.xml file'
  cron:
    name: 'plan.xml daily refresh'
    hour: '3'
    minute: '10'
    job: '/data/plan/update-plan-xml'
- name: 'Executes update-plan-xml'
  shell: /data/plan/update-plan-xml
  args:
    creates: /data/plan/plan.xml

- name: 'Installs cron job for daily refresh of plan.html file'
  cron:
    name: 'plan.html daily refresh'
    hour: '3'
    minute: '15'
    job: '/data/plan/update-plan-html'
- name: 'Executes update-plan-html'
  shell: /data/plan/update-plan-html
  args:
    creates: /data/plan/plan.html

