- name: 'Creates /data/plan directory'
  file:
    path: /data/plan
    state: directory
    mode: 0775

- name: 'Creates /data/plan/logs directory'
  file:
    path: /data/plan/logs
    state: directory
    mode: 0775

- name: 'Copies /data/plan/plan-rss'
  copy:
    src: plan-rss
    dest: /data/plan/plan-rss
    mode: 0700

- name: 'Copies /data/plan/update-dot-plan'
  copy:
    src: update-dot-plan
    dest: /data/plan/update-dot-plan
    mode: 0700

- name: 'Copies /data/plan/update-plan-xml'
  copy:
    src: update-plan-xml
    dest: /data/plan/update-plan-xml
    mode: 0700

- name: 'Installs cron job for daily refresh of plan file'
  cron:
    name: '.plan daily refresh'
    hour: '3'
    minute: '0'
    job: '/data/plan/update-dot-plan'
# Execute this only if plan not present
- name: 'Executes update-dot-plan'
  shell: /data/plan/update-dot-plan

- name: 'Installs cron job for daily refresh of plan file'
  cron:
    name: '.plan daily refresh'
    hour: '3'
    minute: '5'
    job: '/data/plan/update-plan-xml'
# Execute this only if plan.xml not present
- name: 'Executes update-plan-xml'
  shell: /data/plan/update-plan-xml
