- name: 'Creates /data/registry directory'
  file:
    path: /data/registry
    state: directory
    mode: 0775

- name: 'Creates /data/registry/logs directory'
  file:
    path: /data/registry/logs
    state: directory
    mode: 0775

- name: 'Creates /data/registry/certs directory'
  file:
    path: /data/registry/certs
    state: directory
    mode: 0775

- name: 'Creates /data/registry/auth directory'
  file:
    path: /data/registry/auth
    state: directory
    mode: 0775

- name: 'Copies update-registry-certs'
  template:
    src: update-registry-certs.j2
    dest: /data/registry/update-registry-certs
    mode: 0700

- name: 'Installs cron job for daily refresh of registry certificates'
  cron:
    name: 'Registry daily refresh'
    hour: '0'
    minute: '5'
    job: '/data/registry/update-registry-certs'
- name: 'Executes update-registry-certs'
  shell: /data/registry/update-registry-certs
  args:
    creates: /data/registry/certs/domain.key

- include_role:
    name: docker-login

- name: 'Generate /data/registry/auth/htpasswd'
  shell: docker run --entrypoint htpasswd registry:2 -Bbn {{ docker_registry_username }} {{ docker_registry_password }} > /data/registry/auth/htpasswd

- name: 'Runs the registry'
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart: yes
    published_ports:
      - 5000:5000
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /data/registry/auth:/auth
      - /data/registry/certs:/certs
